apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: target-branch
      value: "{{target_branch}}"
  pipelineSpec:
    params:
      - name: git-url
        type: string
      - name: revision
        type: string
      - name: target-branch
        type: string
    workspaces:
      - name: workspace
    tasks:
      - name: clone-repository
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: workspace
        taskRef:
          bundle: quay.io/redhat-appstudio/appstudio-tasks:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3-1
          name: git-clone
      - name: run-tests
        workspaces:
          - name: workspace
            workspace: workspace
        runAfter:
          - clone-repository
        taskSpec:
          workspaces:
            - name: workspace
          steps:
            - name: run-tests
              image: registry.access.redhat.com/ubi8/ubi:latest
              script: cd $(workspaces.workspace.path) && ./automation/test.sh
      - name: run-gitlint
        params:
          - name: git-url
            value: $(params.git-url)
          - name: target-branch
            value: $(params.target-branch)
        workspaces:
          - name: workspace
            workspace: workspace
        runAfter:
          - clone-repository
        taskSpec:
          params:
            - name: target-branch
          workspaces:
            - name: workspace
          steps:
            - name: run-gitlint
              image: registry.access.redhat.com/ubi9/python-39:latest
              workingDir: $(workspaces.workspace.path)
              script: |
                #!/bin/bash -ex

                python -m pip install gitlint
                git remote add upstream "$(params.git-url)"
                git fetch upstream "$(params.target-branch)"
                BASELINE_COMMIT="$(git merge-base HEAD upstream/"$(params.target-branch)")"
                gitlint --commits "$BASELINE_COMMIT"..HEAD
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
