name: Tests to run on Pull Requests
on: pull_request
jobs:
  gitlint:
    name: Run gitlint checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install gitlint into container
        run: python -m pip install gitlint
      - name: Run gitlint check for PR commits
        run: gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD
